Traceback (most recent call last):
  File "C:\Users\gepap\Desktop\Thesis\RL Agent\main.py", line 64, in <module>
    main()
  File "C:\Users\gepap\Desktop\Thesis\RL Agent\main.py", line 42, in main
    forecast_gen = ForecastFeatureGenerator(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Desktop\Thesis\RL Agent\ForecastFeatureGenerator.py", line 18, in __init__
    self.models[target] = tf.keras.models.load_model(model_path)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 155, in load_model_from_hdf5
    **saving_utils.compile_args_from_training_config(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 146, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 205, in _deserialize_nested_config
    return deserialize_fn(config)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\keras\src\losses\__init__.py", line 155, in deserialize
    return serialization_lib.deserialize_keras_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\keras\src\saving\serialization_lib.py", line 575, in deserialize_keras_object
    return deserialize_keras_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\keras\src\saving\serialization_lib.py", line 678, in deserialize_keras_object
    return _retrieve_class_or_fn(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\keras\src\saving\serialization_lib.py", line 810, in _retrieve_class_or_fn
    raise TypeError(
TypeError: Could not locate function 'mse'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`. Full object config: {'module': 'keras.metrics', 'class_name': 'function', 'config': 'mse', 'registered_name': 'mse'}
